baseURL = "https://rmatv.github.io/"
languageCode = "ru-ru"
title = "R.’s"
paginate = 5

DefaultContentLanguage = "en"
copyright = "2017–2022"

pygmentsstyle = "solarized-dark"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

summaryLength = 20

[params]
subtitle = "в гезельшафте киселя не варят"
featherIconsCDN = false
mode = "light" # "dark", "auto", "light"
# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["https://code.jquery.com/jquery-3.4.1.js", "js/custom1.js"]  # Custom JS script

[languages]
  [languages.ru]
    languageName = "Русский"
    title = "Роман Матвиенко"
    weight = 2
    subtitle = "в гезельшафте киселя не варят"

    #[[languages.ru.menu.main]]
    #name = "Главная"
    #url = "/ru/"
    #weight = 1

    [[languages.ru.menu.main]]
    name = "Блог"
    url = "/ru/posts"
    weight = 2
    
    #[[languages.ru]]
    #name = "CV"
    #url = "files/cv_russian.pdf"
    #weight = 3

  [languages.en]
    languageName = "English"
    title = "Roman Matvienko"
    weight = 1
    subtitle = "no kissel is brewed in the _Gesellschaft_"

    #[[languages.en.menu.main]]
    #url    = ""
    #name   = "Home"
    #weight = 1

    [[languages.en.menu.main]]
    url    = "posts"
    name   = "Blog"
    weight = 1

    #[[languages.menu.main]]
    #name = "CV"
    #url = "files/cv_english.pdf"
    #weight = 3

[markup]
  [markup.goldmark.renderer]
    unsafe = true
    math = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
[markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:r.matvienko@link.cuhk.edu.hk"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[permalinks]
posts = "/:year/:month/:slug/"